name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
        sudo rm -rf \
          "$AGENT_TOOLSDIRECTORY" \
          /opt/ghc \
          /usr/lib/jvm \
          /usr/local/.ghcup \
          /usr/local/lib/android \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift >/dev/null 2>&1 || true
        sudo env DEBIAN_FRONTEND=noninteractive apt-get -q -y update >/dev/null 2>&1
        sudo env DEBIAN_FRONTEND=noninteractive apt-get -q -y --purge remove \
          azure-cli \
          dotnet* \
          firefox \
          google-chrome-stable \
          google-cloud-cli \
          microsoft-edge-stable \
          mono-* \
          mysql* \
          postgresql* \
          powershell \
          temurin*  >/dev/null 2>&1 || true
        sudo env DEBIAN_FRONTEND=noninteractive apt-get -q -y --purge autoremove >/dev/null 2>&1 || true
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v3
    - run: source script-linux.sh
#     - run: gh repo clone $GITHUB_REPOSITORY -- --depth 1
    - uses: lhotari/action-upterm@v1
