name: nbdev
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  nbdev:
    container: fastai/jekyll
    runs-on: ubuntu-latest
    steps:
    - name: clone this branch [fastcore]
      uses: actions/checkout@v2
      with:
        repository: 'fastai/fastcore'
        path: fastcore_lib
    - name: clone nbdev
      uses: actions/checkout@v2
      with:
        repository: 'fastai/nbdev'
        path: nbdev
    - name: Install libraries
      run: |
        cd fastcore_lib && pip install -Ue .[dev]
        cd ../nbdev && pip install -Ue .[dev]
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
